services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://164.90.142.68:8080/
    restart: unless-stopped
